workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  stage: build
  image: node:16-alpine # ERR_OSSL_EVP_UNSUPPORTED with node 17 and higher
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build_mogenius
  artifacts:
    paths:
      - www

deploy:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY/copy-pasta1/frontend/copy-pasta-frontend:latest .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/copy-pasta1/frontend/copy-pasta-frontend:latest
